default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  username: <%= ENV['DATABASE_USERNAME'] %>
  username: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: practice_development

test:
  <<: *default
  database: practice_test
